version: '3.5'
services:
  database:
    build: database/
    container_name: database
  api:
    build: api/
    container_name: api
    ports:
      - "8080:8080"
  ui:
    build: ui/
    container_name: ui
    ports:
      - "3000:3000"
